name: "Pull translations from Transifex"

on:
  workflow_dispatch:

jobs:
  pull-translations:
    if: github.repository == 'AnotherSeawhite/Cataclysm-DDA'
    runs-on: ubuntu-22.04
    steps:
      - name: install gettext tools
        run: sudo apt-get install gettext
      - name: "Install Transifex CLI"
        run: |
          curl -sL https://github.com/transifex/cli/releases/download/v1.6.4/tx-linux-amd64.tar.gz | sudo tar zxvf - -C /usr/bin tx
      - name: "Delete existing i18n branch"
        uses: actions/github-script@v6.3.3
        with:
          github-token: ${{ secrets.TX_PR_CREATOR }}
          script: |
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "heads/i18n"
              })
            } catch (error) {
              console.log(error)
            }
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Get current date"
        uses: josStorer/get-current-time@v2.0.2
        id: current-date
        with:
          format: 'DD MMMM YYYY'
      - name: Compile translations (windows)
        run: |
          lang/compile_mo.sh all
      - name: "Upload Translation Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ready-to-use
          path: lang/mo
          compression-level: 0
          overwrite: true
